config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'wlogs/home'
  get 'wlogs/index'
  root 'wlogs#index'
  get 'wlogs/RT'

  resources :wlogs do
    collection { post :import1 }


    collection { post :RT }
  end

  resources :charts, only: [] do
  collection do
    get 'server_throughput'
   
    get 'average_RT'
    get 'error_rate'
    get 'method_RT'


  end
end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    $RT= 3
    $date1
    $date2
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/wlog.rb
class Wlog < ApplicationRecord



def self.apdex(date, date1)
     hash= {}

     data= Wlog.group_by_minute(:Time).where('"RT" != ?', 0).where('"Time" <= ? and "Time" >= ?', date1, date).count
     data1= Wlog.group_by_minute(:Time).where('"RT" != ?', 0).where('"Time" <= ? and "Time" >= ?', date1, date).count
     data2= Wlog.group_by_minute(:Time).where('"RT" != ?', 0).where('"Time" <= ? and "Time" >= ?', date1, date).where('"RT" < ?',   0.3).count
     data3= Wlog.group_by_minute(:Time).where('"RT" != ?', 0).where('"Time" <= ? and "Time" >= ?', date1, date).where('"RT" < ? and "RT" > ?',   1.2, 0.3).count

     #puts data.size, data1.size, data2.size, data3.size


     data.each do |i|
        ts=data1[i[0]]
        sc=data2[i[0]]
        tc=data3[i[0]]



     if sc==nil
           sc=0
     end

     tc=tc.to_f/2
     ap=sc.to_f+tc.to_f
     ap=ap/ts.to_f

     hash[i[0]]=ap
   end
   return hash

end


      def self.import1(file)
        #  CSV.foreach(file.path, headers: true) do |row|
        #    Log.create! row.to_hash
      #    items = []

#items = CSV.read(file.path, headers: true)
    #CSV.foreach(file.path, headers: true) do |row|
    #    items << row.to_h
    #    end
    #    Wlog.import(items)

    batch=[]
    batch_size=6000
    puts "import",  Benchmark.measure {

    CSV.foreach(file.path, liberal_parsing: true, col_sep: " ") do |row|
      date = DateTime.parse(row[3][1..11]+" "+row[3][13..-1])
      rt1= row[10].split("\"")
      rt1= rt1[1].to_f

      u= row[5].split()
        if u[1]
          url_1= u[1].split('?')[0]
        else
          url_1 ='-'
        end

      hash= {:IP => row[0], :Time => date, :URL => u[1],
        :Status => row[6].to_i, :istatus => row[7].to_i, :RT => rt1,
        :Method => u[0], :URL1 =>url_1
         }

      batch.push(hash)

      if batch.size== batch_size
        Wlog.import  batch
        batch=[]
      end


     end
     }
        Wlog.import  batch


      end
















end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController



 



  def server_throughput
    render json: Wlog.group_by_minute(:Time).where('"Time" <= ? and "Time" >= ?',   $date2,   $date1).count
  end

def average_RT
render json: Wlog.group_by_minute(:Time).where('"Time" <= ? and "Time" >= ?', $date2,   $date1).average(:RT)

end

def error_rate

  render json: Wlog.group_by_minute(:Time).where('"Time" <= ? and "Time" >= ?', $date2,   $date1).where('"Status" = ? ', "400").count


end

def method_RT
render json:    Wlog.group(:Method).where('"RT" != ?', 0).where('"Time" <= ? and "Time" >= ?', $date2,   $date1).average(:RT)

end


end

app/controllers/wlogs_controller.rb
class WlogsController < ApplicationController
  before_action :authenticate_user!

  def index


        if params[:date1].present?

  puts "All Record",  Benchmark.measure {
            @date = params[:date1]
            @date_to = params[:date2]
            date=DateTime.parse(@date)
            date1=DateTime.parse(@date_to)
            $date1=date
            $date2=date1
          #  date1= date + 20.minutes
            @Total_Requests=Wlog.where('"Time" <= ? and "Time" >= ?', date1, date).count
            @Null_Requests= Wlog.where('"RT" = ?', 0).where('"Time" <= ? and "Time" >= ?', date1, date).count

            @RT_Threshold_Greater_than_count= Wlog.where('"Time" <= ? and "Time" >= ?', date1, date).where('"RT" > ?',   $RT).count
            @Average_RT =Wlog.where('"Time" <= ? and "Time" >= ?', date1, date).average(:RT)
            @total3 =@total3&.ceil(2)



            @apdex=  Wlog.apdex(date,date1)

            @DataTable_data=Wlog.where('"Time" <= ? and "Time" >= ?', date1, date).where('"RT" > ?',   $RT)


          }

         else
           date1= (a = Wlog.first).present? ? a.Time : 1.hour.ago
           date2= date1 + 20.minutes

           $date1=date1
           $date2=date2

           @Total_Requests= Wlog.where('"Time" <= ? and "Time" >= ?', date2, date1).count
           @Null_Requests= Wlog.where('"RT" = ?', 0).where('"Time" <= ? and "Time" >= ?', date2, date1).count
           @RT_Threshold_Greater_than_count= Wlog.where('"Time" <= ? and "Time" >= ?', date2, date1).where('"RT" > ?',   $RT).count
           @total3 =Wlog.where('"Time" <= ? and "Time" >= ?', date2, date1).average(:RT)
           @total3 = @total3.to_f.ceil(2)





           @apdex= Wlog.apdex(date1,date2)
           @DataTable_data=Wlog.where('"Time" <= ? and "Time" >= ?', date2, date1).where('"RT" > ?',   $RT)




         end

  end

  def home
  end

  def import1
   Wlog.import1(params[:file])
   redirect_to wlogs_path, notice: "Logs Added successfully"
 end


   def import2

    Wlog.import2
    redirect_to wlogs_path, notice: "Logs Added successfully"

  end



  def RT


    if params[:rt1].present?

      $RT= params[:rt1]
      $RT= $RT&.to_f
    end

  end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/wlogs_helper.rb
module WlogsHelper
end

app/views/layouts/_sideMenu.html.erb
        <% if user_signed_in? %>

<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<%=root_path %>">

        <div class="sidebar-brand-text mx-3">Log Analyser <sup>1</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="<%=root_path %>">
        <i class="bi bi-speedometer"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Interface
    </div>

    <!-- Nav Item - Pages Collapse Menu
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
            aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-cog"></i>
            <span>Components</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Components:</h6>
                <a class="collapse-item" href="buttons.html">Buttons</a>
                <a class="collapse-item" href="cards.html">Cards</a>
            </div>
        </div>
    </li>-->

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
            aria-expanded="true" aria-controls="collapseUtilities">
          <i class="bi bi-gear"></i>
            <span>Settings</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
            data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custome Settings:</h6>
                <a class="collapse-item" href="<%= edit_user_registration_path %>">Edit User</a>
                <a class="collapse-item" href="<%= wlogs_RT_path %>">Set RT Threshold</a>

            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading
    <div class="sidebar-heading">
        Addons
    </div> -->

    <!-- Nav Item - Pages Collapse Menu
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
            aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-fw fa-folder"></i>
            <span>Pages</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Login Screens:</h6>
                <a class="collapse-item" href="login.html">Login</a>
                <a class="collapse-item" href="register.html">Register</a>
                <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">Other Pages:</h6>
                <a class="collapse-item" href="404.html">404 Page</a>
                <a class="collapse-item" href="blank.html">Blank Page</a>
            </div>
        </div>
    </li> -->

    <!-- Nav Item - Charts -->
    <li class="nav-item">
        <a class="nav-link" href="<%= wlogs_home_path %>">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Upload Logs</span></a>
    </li>

    <!-- Nav Item - Tables
    <li class="nav-item">
        <a class="nav-link" href="tables.html">
            <i class="fas fa-fw fa-table"></i>
            <span>Tables</span></a>
    </li>-->

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>



</ul>
<!-- End of Sidebar -->

<% end %>

app/views/layouts/_topMenu.html.erb
<% if user_signed_in? %>

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                      <i class="bi bi-justify "></i>
                    </button>

                    <!-- Topbar Search -->
                    



                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">





                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.email%></span>
                              <i class="bi bi-person"></i>
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href= "<%= edit_user_registration_path %>" >
                                  <i class="bi bi-gear" style="color:blue"></i>
                                    Edit Profile
                                </a>
  <!--
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Activity Log
                                </a>-->

                                <a class="dropdown-item" href="<%=destroy_user_session_path %>" data-method="delete" data-toggle="modal" data-target="#logoutModal">
                                  <i class="bi bi-box-arrow-right" style="color:blue" ></i>
                                    Logout
                                </a>

                        </li>

                    </ul>
                    <% end %>

                </nav>
                <!-- End of Topbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
  </head>

  <body id="page-top">

        <div id="wrapper">
              <%= render 'layouts/sideMenu' %>
              <!-- Content Wrapper -->
                <div id="content-wrapper" class="d-flex flex-column">

                      <!-- Main Content -->
                        <div id="content">
                                <%= render 'layouts/topMenu' %>
                                          <%= yield %>
                        </div>
                              <!-- End of Main Content -->

                              <!-- Footer -->
                              <footer class="sticky-footer bg-white">
                                  <div class="container my-auto">
                                      <div class="copyright text-center my-auto">
                                          <span>Copyright &copy; Your Website 2021</span>
                                      </div>
                                  </div>
                              </footer>
                              <!-- End of Footer -->

               </div>
                 <!-- End of Content Wrapper -->

        </div>
        <!-- End of Page Wrapper -->



<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script>



  </body>
</html>

app/views/wlogs/RT.html.erb
  <div class="container-fluid">

                     <!-- Page Heading -->
                     <h1 class="h3 mb-4 text-gray-800">Update Response Time Threshold</h1>
                     <h4 class="h5 mb-4 text-gray-800">Current Value of RT = <%= $RT %> </h4>

                     <%= form_with do |form| %>
                     <%= form.label :query, "RT:" %>
                     <%= form.text_field :rt1 %>

                     <%= submit_tag "Update RT" ,   class:"btn btn-primary mb-2" %>
                     <% end %>

 </div>
                 <!-- /.container-fluid -->

app/views/wlogs/home.html.erb
<!-- Begin Page Content -->
               <div class="container-fluid">

                   <!-- Page Heading -->
                   <h1 class="h3 mb-4 text-gray-800">Log File Upload</h1>






<%= form_tag import1_wlogs_path, class: "form-inline", multipart: true   do %>
  <%= file_field_tag :file    %>


  <%= submit_tag "Upload Logs" ,   class:"btn btn-primary mb-2" %>
<% end %>

 

</div>
<!-- /.container-fluid -->